# Generated by Django 3.2.15 on 2022-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20220927_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='covid19_community_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='covid_cases_per_100k',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='covid_hospital_admissions_per_100k',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='covid_inpatient_bed_utilization',
            field=models.FloatField(null=True),
        ),
    ]
